## Linear Regression for Football Player Salary Prediction and Market Valuation

In [258]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from sympy.benchmarks.bench_discrete_log import data_set_2

In [259]:
attributes = pd.read_csv('../../data/processed/personal_performance_data.csv')
target = pd.read_csv('../../data/processed/wage_euro_target_feature.csv')

In [260]:
attributes.isna().sum()

crossing             0
finishing            0
heading_accuracy     0
short_passing        0
volleys              0
dribbling            0
curve                0
freekick_accuracy    0
long_passing         0
ball_control         0
acceleration         0
sprint_speed         0
agility              0
reactions            0
balance              0
shot_power           0
jumping              0
stamina              0
strength             0
long_shots           0
aggression           0
interceptions        0
positioning          0
vision               0
penalties            0
composure            0
marking              0
standing_tackle      0
sliding_tackle       0
dtype: int64

In [261]:
target.isna().sum()

wage_euro    246
dtype: int64

In [262]:
target = target.fillna(target.mean())

In [263]:
X_train, X_test, y_train, y_test = train_test_split(
    attributes, target, random_state=42, test_size=0.1
)

In [264]:
# Create the Linear Regression model.
model = LinearRegression()

In [265]:
# Train the model using the training data.
model.fit(X_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [266]:
# Predict the target values for the test data.
y_pred = model.predict(X_test)

In [267]:
# Calculate regression evaluation metrics.
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"R2 Score: {r2:.4f}")

MAE: 9087.33
R2 Score: 0.2976


## Linear Regression Model Evaluation

The Linear Regression model achieved a Mean Absolute Error (MAE) of **9,087.33 euros** and an R² score of **0.2976**.

This means that, on average, the model makes an error of around **9,087 euros** when predicting player wages. The R² score shows that the model explains approximately **29.76%** of the variation in the target variable.

Overall, the model has limited predictive performance. It captures some relationship between the selected features and the target, but a large part of the wage variation remains unexplained.

To improve the model, more relevant information should be added. Player wages are not determined only by personal performance statistics. They can also depend on factors such as player reputation, age, club level, league quality, contract status, market value, position, nationality, and overall rating. Adding more informative features could help the model make more accurate predictions.

In [268]:
data_set_2  = pd.read_csv('../../data/processed/clustering_personal_performance_data.csv')
main_dataset = pd.read_csv('../../data/raw/fifa_players.csv')

In [269]:
main_dataset

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
0,L. Messi,Lionel Andrés Messi Cuccittini,6/24/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,...,94,48,22,94,94,75,96,33,28,26
1,C. Eriksen,Christian Dannemann Eriksen,2/14/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,...,89,46,56,84,91,67,88,59,57,22
2,P. Pogba,Paul Pogba,3/15/1993,25,190.50,83.9,"CM,CAM",France,88,91,...,82,78,64,82,88,82,87,63,67,67
3,L. Insigne,Lorenzo Insigne,6/4/1991,27,162.56,59.0,"LW,ST",Italy,88,88,...,84,34,26,83,87,61,83,51,24,22
4,K. Koulibaly,Kalidou Koulibaly,6/20/1991,27,187.96,88.9,CB,Senegal,88,91,...,15,87,88,24,49,33,80,91,88,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,R. McKenzie,Rory McKenzie,10/7/1993,25,175.26,74.8,"RM,CAM,CM",Scotland,67,70,...,54,69,41,60,64,63,56,40,20,18
17950,M. Sipľak,Michal Sipľak,2/2/1996,23,182.88,79.8,LB,Slovakia,59,67,...,22,62,55,42,39,32,52,53,64,60
17951,J. Bekkema,Jan Bekkema,4/9/1996,22,185.42,89.8,GK,Netherlands,59,67,...,9,27,10,5,25,16,47,9,12,13
17952,A. Al Yami,Abdulrahman Al Yami,6/19/1997,21,175.26,64.9,"ST,LM",Saudi Arabia,59,71,...,58,38,15,54,52,50,53,16,18,17


To improve the model performance, we will add several additional features that may have a stronger relationship with player wage prediction.

The new features will include:

- `age` - player age
- `overall_rating` - current overall player rating
- `potential` - estimated future potential
- `value_euro` - estimated market value in euros
- `international_reputation` - international reputation
- `clusters` - we will use dataset with the added clusters

These features are expected to provide more useful information to the model, because player wages are usually influenced not only by personal performance statistics, but also by overall quality, market value, age, and future potential.

In [270]:
additional_features = main_dataset[['age', 'overall_rating', 'potential', 'value_euro', 'international_reputation(1-5)']]

In [271]:
improved_dataset = pd.concat([data_set_2, additional_features], axis=1)
improved_dataset

,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,freekick_accuracy,long_passing,ball_control,...,composure,marking,standing_tackle,sliding_tackle,pp_cluster,age,overall_rating,potential,value_euro,international_reputation(1-5)
0,86,95,70,92,86,97,93,94,89,96,...,96,33,28,26,4,31,94,94,110500000.0,5
1,88,81,52,91,80,84,86,87,89,91,...,88,59,57,22,4,27,88,89,69500000.0,3
2,80,75,75,86,85,87,85,82,90,90,...,87,63,67,67,1,25,88,91,73000000.0,4
3,86,77,56,85,74,90,87,77,78,93,...,83,51,24,22,4,27,88,88,62000000.0,3
4,30,22,83,68,14,69,28,28,60,63,...,80,91,88,87,0,27,88,91,60000000.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,57,61,60,66,37,64,53,47,61,66,...,56,40,20,18,4,25,67,70,975000.0,1
17950,50,19,53,55,31,52,26,28,43,53,...,52,53,64,60,0,23,59,67,190000.0,1
17951,11,9,13,26,9,12,13,12,24,18,...,47,9,12,13,2,22,59,67,170000.0,1
17952,42,60,55,49,49,57,47,39,37,56,...,53,16,18,17,3,21,59,71,280000.0,1


In [272]:
improved_dataset.isna().sum()

crossing                           0
finishing                          0
heading_accuracy                   0
short_passing                      0
volleys                            0
dribbling                          0
curve                              0
freekick_accuracy                  0
long_passing                       0
ball_control                       0
acceleration                       0
sprint_speed                       0
agility                            0
reactions                          0
balance                            0
shot_power                         0
jumping                            0
stamina                            0
strength                           0
long_shots                         0
aggression                         0
interceptions                      0
positioning                        0
vision                             0
penalties                          0
composure                          0
marking                            0
s

In [273]:
pp_clusters_ohe = pd.get_dummies(
    improved_dataset['pp_cluster'],
    prefix='pp_cluster',
    dtype=int
)
improved_dataset = pd.concat([improved_dataset, pp_clusters_ohe], axis=1)
improved_dataset = improved_dataset.drop(columns=['pp_cluster'])

In [274]:
improved_dataset

,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,freekick_accuracy,long_passing,ball_control,...,age,overall_rating,potential,value_euro,international_reputation(1-5),pp_cluster_0,pp_cluster_1,pp_cluster_2,pp_cluster_3,pp_cluster_4
0,86,95,70,92,86,97,93,94,89,96,...,31,94,94,110500000.0,5,0,0,0,0,1
1,88,81,52,91,80,84,86,87,89,91,...,27,88,89,69500000.0,3,0,0,0,0,1
2,80,75,75,86,85,87,85,82,90,90,...,25,88,91,73000000.0,4,0,1,0,0,0
3,86,77,56,85,74,90,87,77,78,93,...,27,88,88,62000000.0,3,0,0,0,0,1
4,30,22,83,68,14,69,28,28,60,63,...,27,88,91,60000000.0,3,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,57,61,60,66,37,64,53,47,61,66,...,25,67,70,975000.0,1,0,0,0,0,1
17950,50,19,53,55,31,52,26,28,43,53,...,23,59,67,190000.0,1,1,0,0,0,0
17951,11,9,13,26,9,12,13,12,24,18,...,22,59,67,170000.0,1,0,0,1,0,0
17952,42,60,55,49,49,57,47,39,37,56,...,21,59,71,280000.0,1,0,0,0,1,0


In [275]:
improved_dataset.isna().sum()

crossing                           0
finishing                          0
heading_accuracy                   0
short_passing                      0
volleys                            0
dribbling                          0
curve                              0
freekick_accuracy                  0
long_passing                       0
ball_control                       0
acceleration                       0
sprint_speed                       0
agility                            0
reactions                          0
balance                            0
shot_power                         0
jumping                            0
stamina                            0
strength                           0
long_shots                         0
aggression                         0
interceptions                      0
positioning                        0
vision                             0
penalties                          0
composure                          0
marking                            0
s

In [276]:
improved_dataset['value_euro'] = improved_dataset['value_euro'].fillna(improved_dataset['value_euro'] .mean())

In [277]:
X_train, X_test, y_train, y_test = train_test_split(improved_dataset, target, random_state=42, train_size=0.25)

In [278]:
improved_dataset

,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,freekick_accuracy,long_passing,ball_control,...,age,overall_rating,potential,value_euro,international_reputation(1-5),pp_cluster_0,pp_cluster_1,pp_cluster_2,pp_cluster_3,pp_cluster_4
0,86,95,70,92,86,97,93,94,89,96,...,31,94,94,110500000.0,5,0,0,0,0,1
1,88,81,52,91,80,84,86,87,89,91,...,27,88,89,69500000.0,3,0,0,0,0,1
2,80,75,75,86,85,87,85,82,90,90,...,25,88,91,73000000.0,4,0,1,0,0,0
3,86,77,56,85,74,90,87,77,78,93,...,27,88,88,62000000.0,3,0,0,0,0,1
4,30,22,83,68,14,69,28,28,60,63,...,27,88,91,60000000.0,3,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,57,61,60,66,37,64,53,47,61,66,...,25,67,70,975000.0,1,0,0,0,0,1
17950,50,19,53,55,31,52,26,28,43,53,...,23,59,67,190000.0,1,1,0,0,0,0
17951,11,9,13,26,9,12,13,12,24,18,...,22,59,67,170000.0,1,0,0,1,0,0
17952,42,60,55,49,49,57,47,39,37,56,...,21,59,71,280000.0,1,0,0,0,1,0


In [279]:
# improved_dataset.to_csv('improved_dataset_with_ohe_clusters.csv', index=False)

In [280]:
model_2 = LinearRegression()

In [281]:
model_2.fit(X_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [282]:
# Predict the target values for the test data.
y_pred = model_2.predict(X_test)

# Calculate regression evaluation metrics.
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"R2 Score: {r2:.4f}")

MAE: 4869.35
R2 Score: 0.7618


## Improved Linear Regression Model Evaluation

After adding additional features to the dataset, the Linear Regression model performance improved significantly.

The updated model achieved a **Mean Absolute Error (MAE) of 4,869.35 euros** and an **R² score of 0.7618**.

Compared to the initial model, where the MAE was **9,087.33 euros** and the R² score was **0.2976**, the new model performs much better. The average prediction error decreased by approximately **4,218 euros**, and the model now explains around **76.18%** of the variation in player wages.

This improvement shows that the added features provide much stronger information for wage prediction. Features such as `age`, `overall_rating`, `potential`, `value_euro`, and `international_reputation` help the model better understand the factors that influence player wages.

The result also confirms that player wages are not determined only by personal performance statistics. They are also strongly influenced by the player's overall quality, market value, future potential, age, and international reputation.

Overall, the improved model has much better predictive performance and is significantly more suitable for wage prediction than the initial model.

In [283]:
predictions_df = pd.DataFrame({
    'actual_wage_euro': np.ravel(y_test),
    'predicted_wage_euro': np.ravel(y_pred)
}, index=X_test.index)

predictions_df.head()

,actual_wage_euro,predicted_wage_euro
9834,2000.0,3386.846546
5815,1000.0,2754.765914
4093,6000.0,2191.154870
7476,1000.0,911.190095
16455,22000.0,11829.900602


In [284]:
predictions_df['error'] = (
    predictions_df['actual_wage_euro'] - predictions_df['predicted_wage_euro']
)

predictions_df['absolute_error'] = predictions_df['error'].abs()

predictions_df.head()

,actual_wage_euro,predicted_wage_euro,error,absolute_error
9834,2000.0,3386.846546,-1386.846546,1386.846546
5815,1000.0,2754.765914,-1754.765914,1754.765914
4093,6000.0,2191.154870,3808.845130,3808.845130
7476,1000.0,911.190095,88.809905,88.809905
16455,22000.0,11829.900602,10170.099398,10170.099398


In [285]:
predictions_df.sort_values(
    by='absolute_error',
    ascending=False
).head(20)

,actual_wage_euro,predicted_wage_euro,error,absolute_error
0,565000.0,344255.570999,220744.429001,220744.429001
17938,455000.0,262480.619162,192519.380838,192519.380838
17924,355000.0,198612.648991,156387.351009,156387.351009
17931,310000.0,160261.163981,149738.836019,149738.836019
10,315000.0,177487.773882,137512.226118,137512.226118
17928,340000.0,208512.972724,131487.027276,131487.027276
54,205000.0,87292.233356,117707.766644,117707.766644
17,200000.0,82978.459378,117021.540622,117021.540622
17934,355000.0,244251.444394,110748.555606,110748.555606
17884,28000.0,128953.613079,-100953.613079,100953.613079


In [286]:
main_dataset

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
0,L. Messi,Lionel Andrés Messi Cuccittini,6/24/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,...,94,48,22,94,94,75,96,33,28,26
1,C. Eriksen,Christian Dannemann Eriksen,2/14/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,...,89,46,56,84,91,67,88,59,57,22
2,P. Pogba,Paul Pogba,3/15/1993,25,190.50,83.9,"CM,CAM",France,88,91,...,82,78,64,82,88,82,87,63,67,67
3,L. Insigne,Lorenzo Insigne,6/4/1991,27,162.56,59.0,"LW,ST",Italy,88,88,...,84,34,26,83,87,61,83,51,24,22
4,K. Koulibaly,Kalidou Koulibaly,6/20/1991,27,187.96,88.9,CB,Senegal,88,91,...,15,87,88,24,49,33,80,91,88,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17949,R. McKenzie,Rory McKenzie,10/7/1993,25,175.26,74.8,"RM,CAM,CM",Scotland,67,70,...,54,69,41,60,64,63,56,40,20,18
17950,M. Sipľak,Michal Sipľak,2/2/1996,23,182.88,79.8,LB,Slovakia,59,67,...,22,62,55,42,39,32,52,53,64,60
17951,J. Bekkema,Jan Bekkema,4/9/1996,22,185.42,89.8,GK,Netherlands,59,67,...,9,27,10,5,25,16,47,9,12,13
17952,A. Al Yami,Abdulrahman Al Yami,6/19/1997,21,175.26,64.9,"ST,LM",Saudi Arabia,59,71,...,58,38,15,54,52,50,53,16,18,17


To further improve the model, we will add one more feature to the dataset: `international_reputation`.

This feature can provide additional information about how well-known and respected a player is internationally. Player reputation may have an important influence on wages, because more recognizable players often receive higher salaries due to their marketability, experience, and overall status in football.

In [287]:
predictions_df.sort_values(
    by='absolute_error',
    ascending=True
)

,actual_wage_euro,predicted_wage_euro,error,absolute_error
4744,1000.0,999.982167,0.017833,0.017833
16066,8000.0,7999.921627,0.078373,0.078373
6719,1000.0,1000.126605,-0.126605,0.126605
11262,2000.0,1999.468117,0.531883,0.531883
3611,2000.0,1999.436003,0.563997,0.563997
...,...,...,...,...
10,315000.0,177487.773882,137512.226118,137512.226118
17931,310000.0,160261.163981,149738.836019,149738.836019
17924,355000.0,198612.648991,156387.351009,156387.351009
17938,455000.0,262480.619162,192519.380838,192519.380838
